spring:
    datasource:
        url: jdbc:mysql://192.168.116.10:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        properties:
             hibernate:
                 hbm2ddl:
                     auto: create
                 show_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    redis:
        host: localhost
        port: 6379
        pool:
             max-idle: 8
             min-idle: 0
             max-active: 8
             max-wait: -1
             
               
         
         
         

     
                   

 
