spring:
    boot:
       demo:
           name: demo
           version: 1.0
           port: 8080
           url: http://localhost:${spring.boot.demo.port}
           # \u968f\u673a\u5b57\u7b26\u4e32
           value: ${random.value}
           # \u968f\u673aint
           number: ${random.int}
           # \u968f\u673along
           bignumber: ${random.long}
           # 10\u4ee5\u5185\u7684\u968f\u673a\u6570
           test1: ${random.int(10)}
           # 10-20\u7684\u968f\u673a\u6570
           test2: ${random.int[10,20]}
           

 
