spring:
    datasource:
        url: jdbc:mysql://192.168.116.10:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        
management:
    security:
        enabled: false
             
               
         
         
         

     
                   

 
